 <?php
 // module/Jeux/view/jeux/jeux/add.phtml:

 $title = 'Ajouter un jeu';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('jeux', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('titre'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('plateforme'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>