 <?php
 // module/Avis/view/avis/avis/edit.phtml:

 $title = 'Edit';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'avis',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('titre'));
 echo $this->formRow($form->get('note'));
 echo $this->formRow($form->get('avis'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>