 <?php
 // module/Avis/view/avis/avis/index.phtml:

 $title = 'Mes avis';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('avis', array('action'=>'add'));?>">Ajouter un avis</a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Note</th>
     <th>Avis</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($aviss as $avis) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($avis->titre);?></td>
     <td><?php echo $this->escapeHtml($avis->note);?></td>
     <td><?php echo $this->escapeHtml($avis->avis);?></td>
     <td>
         <a href="<?php echo $this->url('avis',
             array('action'=>'edit', 'id' => $avis->id));?>">Edit</a>
         <a href="<?php echo $this->url('avis',
             array('action'=>'delete', 'id' => $avis->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>