 <?php
 // module/Screenshot/view/screenshot/screenshot/add.phtml:

 $title = 'Ajouter un screenshot';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('screenshot', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('jeu'));
 echo $this->formRow($form->get('url_image'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>