 <?php
 // module/Screenshot/view/screenshot/screenshot/index.phtml:

 $title = 'Mes screenshot';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('screenshot', array('action'=>'add'));?>">Ajouter un screenshot</a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Screenshot</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($screenshots as $screenshot) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($screenshot->jeu);?></td>
     <td><a href="<?php echo $screenshot->url_image ?>">Voir l'image</a></td>
     <td>
         <a href="<?php echo $this->url('screenshot',
             array('action'=>'edit', 'id' => $screenshot->id));?>">Edit</a>
         <a href="<?php echo $this->url('screenshot',
             array('action'=>'delete', 'id' => $screenshot->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>